pipeline {
    agent any

    environment {
        DOCKER_USER = "mohith4648"
        IMAGE_NAME  = "travel-project"
        TAG         = "v1"
        CRED_ID     = "dockerentry" 
    }

    stages {
        stage('1. Setup') {
            steps {
                cleanWs()
                git branch: 'main', url: 'https://github.com/Mohith4648/travel-website.git'
            }
        }

        stage('2. Build & Push Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${env.CRED_ID}", 
                                 passwordVariable: 'DOCKER_PASS', 
                                 usernameVariable: 'DOCKER_USER_VAR')]) {
                    script {
                        sh "docker build -t ${DOCKER_USER}/${IMAGE_NAME}:${TAG} -f nginix/Dockerfile ."
                        sh "echo '${DOCKER_PASS}' | docker login -u '${DOCKER_USER_VAR}' --password-stdin"
                        sh "docker push ${DOCKER_USER}/${IMAGE_NAME}:${TAG}"
                        sh "docker logout"
                    }
                }
            }
        }

       stage('3. Production Deployment') {
    steps {
        script {
            sh "docker rm -f travel-site || true"
            // The mapping: External:Internal
            sh "docker run -d --name travel-site -p 82:80 ${DOCKER_USER}/${IMAGE_NAME}:${TAG}"
        }
    }
}
    }
}
